language: node_js

node_js:
  - '10'
  - '8'

script:
  - npm run test:ci
  - npm run build
  - npm run check

install:
  - npm ci

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
